# Generated by Django 5.0.14 on 2025-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_license_plate_licenseplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("owner", "Garage Owner"), ("customer", "Garage User")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
