# Generated by Django 5.0.14 on 2025-09-25 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="garage.booking"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="garage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="garage.garage"
            ),
        ),
    ]
