# Generated by Django 5.0.14 on 2025-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0004_booking_cancelled_garage_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
