# Generated by Django 5.0.14 on 2025-09-27 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0005_booking_cancel_reason_booking_cancelled_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "stream_url",
                    models.CharField(
                        help_text="HTTP/MJPEG/iframe URL or vendor web UI URL",
                        max_length=500,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
