# Generated by Django 5.0.14 on 2025-09-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0006_camera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="stream_url",
            field=models.CharField(max_length=500),
        ),
    ]
