# Generated by Django 5.0.14 on 2025-09-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0007_alter_camera_stream_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarageActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GarageFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="garage",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="garage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="garages/"),
        ),
        migrations.AddField(
            model_name="garage",
            name="price_per_hour",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="garage",
            name="activities",
            field=models.ManyToManyField(
                blank=True, related_name="garages", to="garage.garageactivity"
            ),
        ),
        migrations.AddField(
            model_name="garage",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="garages", to="garage.garagefeature"
            ),
        ),
    ]
