# Generated by Django 5.0.14 on 2025-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0008_garageactivity_garagefeature_garage_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarageAllowedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GarageForbiddenActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GarageTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="garage",
            name="activities",
        ),
        migrations.RemoveField(
            model_name="garage",
            name="features",
        ),
        migrations.AlterField(
            model_name="garage",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="garage",
            name="allowed_activities",
            field=models.ManyToManyField(
                blank=True, related_name="garages", to="garage.garageallowedactivity"
            ),
        ),
        migrations.AddField(
            model_name="garage",
            name="forbidden_activities",
            field=models.ManyToManyField(
                blank=True, related_name="garages", to="garage.garageforbiddenactivity"
            ),
        ),
        migrations.AddField(
            model_name="garage",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="garages", to="garage.garagetool"
            ),
        ),
        migrations.DeleteModel(
            name="GarageActivity",
        ),
        migrations.DeleteModel(
            name="GarageFeature",
        ),
    ]
