# Generated by Django 5.0.14 on 2025-09-25 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanlinessCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("before_image", models.ImageField(upload_to="cleanliness/before/")),
                ("after_image", models.ImageField(upload_to="cleanliness/after/")),
                ("passed", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="garage.booking"
                    ),
                ),
            ],
        ),
    ]
