# Generated by Django 5.0.14 on 2025-09-25 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Toolbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Main Toolbox", max_length=100)),
                (
                    "weight_ref",
                    models.FloatField(help_text="Reference weight in grams"),
                ),
                ("last_measured_weight", models.FloatField(default=0.0)),
                ("last_check_ok", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name="toolusagelog",
            name="tool",
        ),
        migrations.RemoveField(
            model_name="toolusagelog",
            name="user",
        ),
        migrations.DeleteModel(
            name="Tool",
        ),
        migrations.DeleteModel(
            name="ToolUsageLog",
        ),
    ]
